### ISSUE TITLE
EqualTo field not saving

### ISSUE THREAD

**Issue by tardinha** [xini/silverstripe-userforms-confirmemailfield#3] opened 2016-08-15 05:05 UTC
Hi,

I have this module installed in an empty 3.2 install. When I add an email confirm field, set it's must be equal to field to another email, then save, that value is not saving.

Cheers

Mark

**Comment by xini** [comment] 2016-08-15 05:10
Hi Mark,
What version of userforms are you using?
Cheers, Flo

**Comment by tardinha** [comment] 2016-08-15 05:12
3

**Comment by xini** [comment] 2016-08-15 05:13
no worries. I'll check..

**Comment by xini** [comment] 2016-08-15 08:40
Hi Mark,
Fixed in version 2.0.1. caused by legacy code... sorry...
Cheers Flo

**Closed as completed by xini** 2016-08-15 08:40 UTC
